Add Requires(pre): /bin/sh
Getting this package installed by a rootfs boostrapping would show:

 DEBUG util.py:461:  error: failed to exec scriptlet interpreter /bin/sh: No such file or directory
 DEBUG util.py:461:  error: %prein(crypto-policies-20250214-1.gitfd9b9b9.el10_0.1.noarch) scriptlet failed, exit status 127
 DEBUG util.py:459:  Error in PREIN scriptlet in rpm package crypto-policies
 DEBUG util.py:461:  error: crypto-policies-20250214-1.gitfd9b9b9.el10_0.1.noarch: install failed