Add Requires(pre): glibc
xcp-ng-release currently has dependencies that create dependency
loops, which RPM silently handles without even a warning, by breaking
the loop "where it can".

On an Alma10 base the RPM heuristics for breaking the loop start to
fail, and Getting this package installed by a rootfs boostrapping
would show:

 DEBUG util.py:461:  error: failed to exec scriptlet interpreter /bin/sh: No such file or directory
 DEBUG util.py:461:  error: %prein(crypto-policies-20250214-1.gitfd9b9b9.el10_0.1.noarch) scriptlet failed, exit status 127
 DEBUG util.py:459:  Error in PREIN scriptlet in rpm package crypto-policies
 DEBUG util.py:461:  error: crypto-policies-20250214-1.gitfd9b9b9.el10_0.1.noarch: install failed

While /bin/sh is available at that point, glibc is not.  This extra
dependencu nudges the RPM dependency solver to break the loop
somewhere else.  By sheer luck, this is enough.

Full context at https://github.com/rpm-software-management/rpm/issues/4141

Signed-off-by: Yann Dirson <yann.dirson@vates.tech>